### ISSUE TITLE
Incompatible to Symfony 2.0.20+, 2.1.5+, 2.2+

### ISSUE THREAD

**Issue by nickvergessen** [dsyph3r/symblog#11]
The following `{% render 'BloggerBlogBundle:Comment:new' with { 'blog_id': blog.id } %}` from http://tutorial.symblog.co.uk/docs/extending-the-model-blog-comments.html does not work anymore:

An exception has been thrown during the rendering of a template ("No route found for "GET Comment:new"") in BloggerBlogBundle:Blog:show.html.twig at line 24.

See: http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released

**Comment by nickvergessen** [comment]
To Fix, add a new route:

```
BloggerBlogBundle_comment_new:
    pattern:  /new/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:new }
    requirements:
        _method:  GET
        blog_id:  \d+
```

and use
`{% render url('BloggerBlogBundle_comment_new', { 'blog_id': blog.id }) %}`
in the template.
